interface IRegister {
    numero: string,
    task?: string,
    sctask?: string,
    data: string,
    mesaTarefa: string,
    mesaChamado: string,
    status: string,
    analista: string,
    equipe: string,
    supervisor: string,
    classificacao: string,
    sistema: string,
    corrigirArtigo?: string,
    motivo: string,
    justificativa: string,
    analiseSupervisor?: string,
    analiseSniper?: string,
    analiseConclusao?: string
}