interface IRegister {
    numero_chamado: string,
    task: string,
    sctask: string,
    data_chamado?: string,
    data_task?: string,
    mesa_chamado?: string,
    mesa_task?: string,
    status_chamado?: string,
    status_task?: string,
    analista_chamado?: string,
    analista_task: string,
    equipe: string,
    classificacao: string,
    sistema: string,
    motivo: string,
    justificativa: string,
    analise_supervisor?: string,
    analise_sniper?: string,
    analise_conclusao?: string,
    nome_artigo?: string,
    solicitacao_artigo?: string,
    validacao_artigo?: string,
    justificativa_artigo?: string
}