export const registers = [
    {
        numero: "INC001",
        task: "TASK001",
        sctask: "",
        analista: "Andre Luis Fernandes de Souza",
        status: "Resolvido",
        data: "2023-11-27",
        mesaTarefa: "N3-MICROSOFT_OFFICE",
        incidenteRepassado: "",
        mesaChamado: "",
    },
    {
        numero: "INC002",
        task: "TASK002",
        sctask: "",
        analista: "Andre Luis Fernandes de Souza",
        status: "Em andamento",
        data: "2023-11-01",
        mesaTarefa: "N3-N3-SUPORTE_TECNICO_DE_VOZ",
        incidenteRepassado: "",
        mesaChamado: "",
    },
    {
        numero: "INC003",
        task: "TASK003",
        sctask: "",
        analista: "Andre Luis Fernandes de Souza",
        status: "Em andamento",
        data: "2023-11-27",
        mesaTarefa: "N3-MICROSOFT_OFFICE",
        incidenteRepassado: "",
        mesaChamado: "",
    },
    {
        numero: "INC004",
        task: "TASK004",
        sctask: "",
        analista: "Andre Luis Fernandes de Souza",
        status: "Em andamento",
        data: "2023-11-27",
        mesaTarefa: "N3-MICROSOFT_OFFICE",
        incidenteRepassado: "",
        mesaChamado: "",
    },
    {
        numero: "INC005",
        task: "TASK005",
        sctask: "",
        analista: "Andre Luis Fernandes de Souza",
        status: "Resolvido",
        data: "2023-11-27",
        mesaTarefa: "N3-MICROSOFT_OFFICE",
        incidenteRepassado: "",
        mesaChamado: "",
    },
    {
        numero: "INC006",
        task: "TASK006",
        sctask: "",
        analista: "Pedro",
        status: "Resolvido",
        data: "2023-11-27",
        mesaTarefa: "N3-MICROSOFT_OFFICE",
        incidenteRepassado: "",
        mesaChamado: "",
    },
    {
        numero: "INC007",
        task: "TASK007",
        sctask: "",
        analista: "Matheus",
        status: "Resolvido",
        data: "2023-11-27",
        mesaTarefa: "N3-MICROSOFT_OFFICE",
        incidenteRepassado: "",
        mesaChamado: "",
    },
]

export const registersJustified: Object[] = []