export const registers = [
    {
        numero_chamado: "INC001",
        tarefa: "TASK001",
        analista_chamado: "Andre Luis Fernandes de Souza",
        analista_task: "Andre Luis Fernandes de Souza",
        status_chamado: "Em andamento",
        status_task: "Resolvido",
        data_chamado: "2023-11-27",
        data_task: "2023-11-27",
        mesa_task: "N3-MICROSOFT_OFFICE",
        mesa_chamado: "N3-MICROSOFT_OFFICE",
        grupo_spoc: "N1-SD_PADRAO",
        spoc_designado: "Andre Luis Fernandes de Souza"
    },
    {
        numero_chamado: "INC001",
        tarefa: "TASK002",
        analista_chamado: "Andre Luis Fernandes de Souza",
        analista_task: "Andre Luis Fernandes de Souza",
        status_chamado: "Em andamento",
        status_task: "Resolvido",
        data_chamado: "2023-11-27",
        data_task: "2023-11-27",
        mesa_task: "N3-MICROSOFT_OFFICE",
        mesa_chamado: "N3-MICROSOFT_OFFICE",
        grupo_spoc: "N1-SD_PADRAO",
        spoc_designado: "Andre Luis Fernandes de Souza"
    },
    {
        numero_chamado: "INC003",
        tarefa: "TASK003",
        analista_chamado: "Andre Luis Fernandes de Souza",
        analista_task: "Andre Luis Fernandes de Souza",
        status_chamado: "Resolvido",
        status_task: "Resolvido",
        data_chamado: "2023-11-27",
        data_task: "2023-11-27",
        mesa_task: "N3-MICROSOFT_OFFICE",
        mesa_chamado: "N3-MICROSOFT_OFFICE",
        grupo_spoc: "N1-SD_PADRAO",
        spoc_designado: "Andre Luis Fernandes de Souza"
    },
    {
        numero_chamado: "INC004",
        tarefa: "TASK004",
        analista_chamado: "Andre Luis Fernandes de Souza",
        analista_task: "Andre Luis Fernandes de Souza",
        status_chamado: "Resolvido",
        status_task: "Resolvido",
        data_chamado: "2023-11-27",
        data_task: "2023-11-27",
        mesa_task: "N3-MICROSOFT_OFFICE",
        mesa_chamado: "N3-MICROSOFT_OFFICE",
        grupo_spoc: "N1-SD_PADRAO",
        spoc_designado: "Andre Luis Fernandes de Souza"
    },
    {
        numero_chamado: "INC005",
        tarefa: "TASK005",
        analista_chamado: "Andre Luis Fernandes de Souza",
        analista_task: "Andre Luis Fernandes de Souza",
        status_chamado: "Resolvido",
        status_task: "Resolvido",
        data_chamado: "2023-11-27",
        data_task: "2023-11-27",
        mesa_task: "N3-MICROSOFT_OFFICE",
        mesa_chamado: "N3-MICROSOFT_OFFICE",
        grupo_spoc: "N1-SD_PADRAO",
        spoc_designado: "Andre Luis Fernandes de Souza"
    },
    {
        numero_chamado: "INC006",
        tarefa: "TASK006",
        analista_chamado: "Andre Luis Fernandes de Souza",
        analista_task: "Andre Luis Fernandes de Souza",
        status_chamado: "Resolvido",
        status_task: "Resolvido",
        data_chamado: "2023-11-27",
        data_task: "2023-11-27",
        mesa_task: "N3-MICROSOFT_OFFICE",
        mesa_chamado: "N3-MICROSOFT_OFFICE",
        grupo_spoc: "N1-SD_PADRAO",
        spoc_designado: "Andre Luis Fernandes de Souza"
    },
    {
        numero_chamado: "INC007",
        tarefa: "TASK007",
        analista_chamado: "Andre Luis Fernandes de Souza",
        analista_task: "Andre Luis Fernandes de Souza",
        status_chamado: "Resolvido",
        status_task: "Resolvido",
        data_chamado: "2023-11-27",
        data_task: "2023-11-27",
        mesa_task: "N3-MICROSOFT_OFFICE",
        mesa_chamado: "N3-MICROSOFT_OFFICE",
        grupo_spoc: "N1-SD_PADRAO",
        spoc_designado: "Andre Luis Fernandes de Souza"
    },
]

export const registersJustified: Object[] = []